### ISSUE TITLE
[api improvement] userId for exernal user update and delete

### ISSUE THREAD

**Issue by ErikAndreas** [ITfoxtec/FoxIDs#1024]
Allow external users to have email and or upPartyName changed by userId (rather than email + upPartyName beeing joint key/unchangeable)

Also, delete external user by userId would be easier since external parties (api consumers) are more likely to keep (external) userId than both email and upPartyName (for that specific user), upPartyName is something rather internal to FoxIDs and should not have to be kept by api consumers (as opposed to userId)

**Comment by Revsgaard** [comment]
Thank you very much. I agree that it would make it easier to use the external user API functionality.
