### ISSUE TITLE
PostgreSQL repository failure to filter tenants

### ISSUE THREAD

**Issue by bjornharrtell** [ITfoxtec/FoxIDs#1041]
Local reproduction results in following unhandled exception:

fail: FoxIDs.Infrastructure.Logging.StdoutTelemetryLogger[0]
      Timestamp: 2024-11-20T10:57:26.527Z
      System.Exception: Failing route request path '/master/master/!filtertenant'.
       ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at lambda_method327(Closure, Tenant)
         at FoxIDs.Repository.PgTenantDataRepository.<>c__DisplayClass7_0`1.<GetListAsync>b__0(T d) in /home/bjorn/code/FoxIDs-upstream/src/FoxIDs.Shared/Repository/PostgreSql/PgTenantDataRepository.cs:line 107

**Comment by bjornharrtell** [comment]
Current investigation for the listing/filter issue is that ForUsage for tenant is expected to be true but is persisted false. Any ideas about that @Revsgaard?

**Comment by bjornharrtell** [comment]
If I manipulate the persisted value ForUsage to be true it works including filtering. So it seems the cause is indeed that ForUsage is set to false unexpectedly, but I can't understand how that can be something that is specific for PostgreSQL repository. Other boolean properties on other entities seems to work fine.

**Comment by Revsgaard** [comment]
All tests and test applications run perfectly :)

What do you think about popping your PgKeyValueDB library to version 1.x.x?

**Comment by Revsgaard** [comment]
PG code merged into https://github.com/ITfoxtec/FoxIDs/tree/1.12.x-development

**Comment by bjornharrtell** [comment]
@Revsgaard I've pushed a version 1.0.0. The only change is removal of a left over console writeline I had forgot to remove.. :)

**Comment by bjornharrtell** [comment]
See https://github.com/ITfoxtec/FoxIDs/pull/1045

**Comment by bjornharrtell** [comment]
Sounds like this can be closed. 🙂
