### ISSUE TITLE
Question: Assistance with Extending SAML AuthnRequest for AppSwitch Property

### ISSUE THREAD

**Issue by VolodymyrPavliukevych** [ITfoxtec/FoxIDs#1048]
FoxIDs community,

I am reaching out for assistance with extending a SAML AuthnRequest to include custom fields.

According to the [NemLog-in](https://cms.nemlog-in.dk/media/jhmbnulm/integration-with-nemlog-in.pdf) documentation (https://cms.nemlog-in.dk/media/jhmbnulm/integration-with-nemlog-in.pdf) for the app switch feature (9.7 Mobile app-switch), I need to add the AppSwitch property to the SAML request.

However, I am using FoxIDs as an OpenID-to-SAML service and cannot find a way to include the AppSwitch property in the requests FoxIDs generates for the third-party IdP.

It should be like:
```
<?xml version="1.0"?>
<samlp:AuthnRequest
ID="id9eb5dd256c25461584a2796994feab1d"
...
xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
<saml:Issuer>https://sp3.dev-nemlog-in.dk</saml:Issuer>
<samlp:Extensions>
  <nl:AppSwitch xmlns:nl="https://data.gov.dk/eid/saml/extensions">
    <nl:Platform>Android</nl:Platform>
    <nl:ReturnURL>dk.serviceprovider.test</nl:ReturnURL>
  </nl:AppSwitch>
</samlp:Extensions>
...
</samlp:AuthnRequest>
```
Could you kindly guide me on how to achieve this?

Thank you for your support!

**Comment by Revsgaard** [comment]
Thanks for your question, answered on [stackoverflow](https://stackoverflow.com/questions/79208632/assistance-with-extending-saml-authnrequest-for-appswitch-property).

**Comment by VolodymyrPavliukevych** [comment]
Thanks a lot!
