### ISSUE TITLE
Replace Microsoft.Azure.ApplicationInsights.Query dependency

### ISSUE THREAD

**Issue by scottaddie** [ITfoxtec/FoxIDs#315]
Last week, the Azure SDK team deprecated Microsoft.Azure.ApplicationInsights.Query in favor of [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query). Please make plans to migrate. Migration guidance has been provided at https://aka.ms/azsdk/net/migrate/ai-monitor-query.

Per [this announcement](https://azure.microsoft.com/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/), support for this deprecated package ends on March 31, 2023.

**Comment by Revsgaard** [comment]
Thank you for det information. I'll make planes to migration .
