### ISSUE TITLE
Make it possible to customize emails send from FoxIDs.

### ISSUE THREAD

**Issue by Revsgaard** [ITfoxtec/FoxIDs#407]
More info?

**Comment by nshiva** [comment]
More info please.

**Comment by Revsgaard** [comment]
The following describe the possibilities today, do you need more customization?

---------

You can change the different e-mail texts (translations) on tenant level depending on language. It is also possible to add HTML tags.

Doc: https://www.foxids.com/docs/language#translation-in-track

E.g. like this:
![image](https://github.com/ITfoxtec/FoxIDs/assets/9498173/0f6b1dbc-c34f-4973-8b8d-c18055e8c4a8)

The required `{0}` element is the company name if specified in the tenant:
![image](https://github.com/ITfoxtec/FoxIDs/assets/9498173/899dd766-2063-430f-bc76-0adcddba6e82)
