### ISSUE TITLE
Cannot deploy to Basic SKU / make slots optional

### ISSUE THREAD

**Issue by bjornharrtell** [ITfoxtec/FoxIDs#470]
Looks like it's not possible to deploy the ARM template using a Basic SKU, likely due to the slots usage.

Error message from deployment:
```
##[error]Details:
##[error]undefined: Cannot complete the operation because the site will exceed the number of slots allowed for the 'Basic' SKU.
```

Rationale is that it might not be desireable to use slots at all.

**Comment by Revsgaard** [comment]
I do not think ARM support IF ELSE statement on other then values. Unfortunately, it seems that it is not possible to have IF ELSE around resource creation.
A solution could be to remove the Basic SKU and smaller. OR maybe change to use Terraform, but I haven't looked in to Terraform or used it before.

**Comment by bjornharrtell** [comment]
Agreed this seems to not be something we want short or long term.
