### ISSUE TITLE
Logout flow leads to: 'Failing route request path' error

### ISSUE THREAD

**Issue by VolodymyrPavliukevych** [ITfoxtec/FoxIDs#602]
Dear @Revsgaard, I want to share with you issue we faced with: `Failing route request path`.

We are using latest FoxIDs `1.0.17.2` version.
IDP: `KOMBIT`
URL party binding pattern: `Dot pattern .../down-party.up-party./...`
Logout Service Kind: `HTTP-Redirect`.
Metadata was uploaded and validated in KOMBIT portal.
(If we are using POST Logout, KOMBIT can't validate that metadata)
Error description:

![FoxIDs-logout-KOMBIT-issue](https://github.com/ITfoxtec/FoxIDs/assets/1786378/86cfdedb-5268-40d5-820c-8fcc120d8020)

Please, take a look on that issue, I will be happy for any helpful answer.
Thank you!

**Comment by Revsgaard** [comment]
Currently, Context Handler has an bug where it logs out with a post binding event if you configure a redirect binding. Therefore, after successfully configuration in Context Handler, you need to change the Logout response binding back to post in order to make logout work.

**Comment by VolodymyrPavliukevych** [comment]
Thank you for your answer. Will wait for improvements.

**Comment by Revsgaard** [comment]
I don't know if Context Handler will fix this error, but with this workaround you can move forward.
