### ISSUE TITLE
Adding OIDC up-party with more than 10 keys fails

### ISSUE THREAD

**Issue by magohl** [ITfoxtec/FoxIDs#710]
Trying to add an up-party of type OIDC and get this error:

``Failing route request path '/xyz/test/!oidcupparty'.; OidcUpParty: [Keys: The field Keys must be between 1 and 10.]``

The difference compared to one that work is that it has more than 10 'keys' in the jwks document which the error also clearly indicates. Are there any specific reasons for having a maximum of 10 and are there any way to increase it?

Thanks for a great product!

**Comment by Revsgaard** [comment]
It is possible to expand de number of supported keys.
How many keys do the external party expose in there OIDC Discovery?

**Comment by magohl** [comment]
For some strange reason this one has 26 (!). I have not yet looked in detail in the jwks document to see if i can figure out any reason behind the large number, i have only counted them.

This is from the test environment on one of the 'big' MitId/BankId providers.

**Comment by Revsgaard** [comment]
that's a lot of keys :) I have added support for up to 50 keys in commit https://github.com/ITfoxtec/FoxIDs/commit/29f756a512ed20ea3a2fc594ecade4f4a2a30d85

**Comment by magohl** [comment]
Thanks!

**Comment by Revsgaard** [comment]
Released in version [1.2.5](https://github.com/ITfoxtec/FoxIDs/releases/tag/1.2.5) and active on FoxIDs.com

**Comment by magohl** [comment]
Validated with the example i used and it is working great on FoxIDs.com now with 26 (!) keys!
