### ISSUE TITLE
Unit tests should work out of the box + continuous testing

### ISSUE THREAD

**Issue by bjornharrtell** [ITfoxtec/FoxIDs#740]
Cloning the repository and building out of the box works but a `dotnet test` run fails most tests with final output:

Failed!  - Failed:   141, Passed:    12, Skipped:     0, Total:   153, Duration: 461 ms - FoxIDs.UnitTests.dll (net8.0)

As of yet I have no clue why it fails so severely.

It would be good if that just worked and it would be good if ensured by public github action test run on all commits / PRs or similar.

**Comment by Revsgaard** [comment]
You are right.
The general unit test error is corrected in commit https://github.com/ITfoxtec/FoxIDs/commit/7acdc002401a10a14c9e88a2019e63a1888feb51

**Comment by bjornharrtell** [comment]
Verified fix here:

Passed!  - Failed:     0, Passed:   153, Skipped:     0, Total:   153, Duration: 5 s - FoxIDs.UnitTests.dll (net8.0)

:)
