### ISSUE TITLE
FoxIDs should be runnable out of the box without external dependencies

### ISSUE THREAD

**Issue by bjornharrtell** [ITfoxtec/FoxIDs#741]
Cloning the repository and attempting to run FoxIDs with `dotnet run` fails with:

Unhandled exception. Azure.Identity.CredentialUnavailableException: DefaultAzureCredential failed to retrieve a token from the included credentials

I suspect this is related to dependency on Azure Keyvault so this is related to https://github.com/ITfoxtec/FoxIDs/issues/471#issuecomment-1318452353.

I think it would be good if it could fall back to something local and simple for development purposes. That would also allow for automated integration tests.

**Comment by bjornharrtell** [comment]
Running with `ASPNETCORE_ENVIRONMENT=Development dotnet run` avoid this error and it's reasonable to require setting that env var for development purposes. I still feel it would be good if Azure Keyvault usage would be an opt in pluggable thing.

However next blocker is it now fails with:

Unhandled exception. StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s)

So same situation but with Redis dependency.

**Comment by Revsgaard** [comment]
I agreed, it is a good idea to be able do run without Azure Keyvault.

And also nice if Redis could be optional.

**Comment by bjornharrtell** [comment]
@Revsgaard I suppose this can be closed?

**Comment by Revsgaard** [comment]
Yes I agree.
