### ISSUE TITLE
Pluggable cache backend + Redis alternative

### ISSUE THREAD

**Issue by bjornharrtell** [ITfoxtec/FoxIDs#742]

**Comment by bjornharrtell** [comment]
I now find that Redis also supplies a pub/sub mechanism and it's used in some places. So, Redis cannot be replaced by a simple key value caching mechanism.

**Comment by bjornharrtell** [comment]
A possible replacement is https://rebus.fm/what-is-rebus/. Unfortunately while it has both in mem built in or can act as abstraction for all kinds of message services, Redis is not one of them. I will attempt to make a generic interface.

**Comment by bjornharrtell** [comment]
I also now find that abstraction `IDistributedCache` is used on top of Redis in `SequenceLogic`, which might be an indication that the cache is intended to be cross process.

**Comment by bjornharrtell** [comment]
@Revsgaard I suppose this can be closed?

**Comment by Revsgaard** [comment]
Yes I agree.
