### ISSUE TITLE
CreateAsync in PgTenantDataRepository and PgMasterDataRepository should fail if the ID already exists

### ISSUE THREAD

**Issue by Revsgaard** [ITfoxtec/FoxIDs#781]
The CreateAsync method should fail if the ID already exists by throwing the FoxIDsDataException exception.

`throw new FoxIDsDataException(id, partitionId) { StatusCode = DataStatusCode.Conflict };`

It applies to both PgTenantDataRepository and PgMasterDataRepository.

**Comment by Revsgaard** [comment]
@bjornharrtell how is this fixed the best way. Maybe some functionality is needed in the PgKeyValueDB component?

**Comment by bjornharrtell** [comment]
I have a tentative PR on the above that allows to opt out of upsert... but I feel it's a bit strange, I thought upsert was how key value stores usually worked and the Set method kind of implies it. Would perhaps be more appropriate with Create and Update methods instead?

**Comment by Revsgaard** [comment]
It is probably better to have Create and Update/Replace instead. And then have Upsert/Save separately.

**Comment by bjornharrtell** [comment]
Agreed and done, released as 0.5.0.

**Comment by bjornharrtell** [comment]
I've reworked handling of the known error case in 0.6.0 so that Create will simply return true or false where false only known reason is duplicate key.

**Comment by Revsgaard** [comment]
That's great, thanks. Updated in commit [7f90f05](https://github.com/ITfoxtec/FoxIDs/commit/7f90f0546bf97ccc3a3b9ae81a176661eaf476cd), this should be correct?

**Comment by bjornharrtell** [comment]
Yep look fine to me!
