### ISSUE TITLE
Urgent: Can't create new application (down-party)

### ISSUE THREAD

**Issue by alex-kur** [ITfoxtec/FoxIDs#847]
Looks like a bug after the last update. I can't create new down-parties.
Steps to reproduce:
1. Create new environment
2. Add new application to environment (it saves without any errors)
3. Refresh the page - application is gone

**Comment by Revsgaard** [comment]
Thank you for reporting the problem, it is resolved in [release 1.6.9](https://github.com/ITfoxtec/FoxIDs/releases/tag/1.6.9).
