### ISSUE TITLE
PostgreSQL support broken in foxids/foxids-control docker image?

### ISSUE THREAD

**Issue by bjornharrtell** [ITfoxtec/FoxIDs#983]
I'm trying to run latest FoxIDs as containers and run into an issue that a dependency seems to be missing?

I can get the foxids/foxids container up and running with configured PostgreSql for Cache and DataStorage, but failing with foxids/foxids-control. I see the following in logs from foxids/foxids-control container:

Background PostgreSQL data queue error.
  Warning
2024-10-24T10:55:08.8912503
      System.InvalidOperationException: No service for type 'FoxIDs.Repository.PgTenantDataRepository' has been registered.

Tested version is 1.10.12.

**Comment by Revsgaard** [comment]
Thank you for the error.

The repository was loaded incorrect, this commit should solve the problem https://github.com/ITfoxtec/FoxIDs/commit/7bebc6a8ff39761a05271a036d8735ea3a723c51 (ignore the ARM part).

**Comment by Revsgaard** [comment]
You can test the new version with the two test Docker images foxids/foxids:latest-test and foxids/foxids-control:latest-test

Please let me know if et works :)

**Comment by bjornharrtell** [comment]
Confirmed control seems to startup with issues now.

I'm however now having other issues.. that might be because how to attempt to set this up. I use two independent azure web app containers.. the main foxid container seems confused about http/https with them mixed in the openid-configuration:

![image](https://github.com/user-attachments/assets/7188c05d-3e9d-4834-8bba-ff805a35c6e6)

But perhaps this is not even a supported scenario considering Settings__FoxIDsBackendEndpoint usually seem to point to an internal network host? But that doesn't seem related to the above http/https mixup...

**Comment by bjornharrtell** [comment]
Hold on, seems setting `Settings__TrustProxySchemeHeader` to true resolves the http/https mixup. :)

**Comment by Revsgaard** [comment]
Okay great. Then I'll make a release ready with the update.

**Comment by Revsgaard** [comment]
Released in version [1.10.13](https://github.com/ITfoxtec/FoxIDs/releases/tag/1.10.13).

Docker images `foxids/foxids:latest` and `foxids/foxids-control:latest` as usual.
