### ISSUE TITLE
Add API method that returns all tracks

### ISSUE THREAD

**Issue by alex-kur** [ITfoxtec/FoxIDs#991]
Please add a new API method that can return all registered tracks.

My situation:
I created a console tool that works with the FoxIDs API to automate some of my routine tasks. For example, creating and setting up new tracks using a template, backups all tracks settings (I store all track settings in JSON files), updating down-party redirect URIs, etc.
At the moment I use the API method `!FilterTrack` without params to get all registered tracks in my tool, but it can only return the first 50 tracks (as far as I remember). And for now I already have 47 registered tracks. So my tool will stop working soon))

It would be nice to have some API method that could return a list of all registered tracks (with or without paging). Actually, for my tool it will be enough to get a list of all registered track names, but it will be cool if the method returns a list of `Track` objects.

Thanks in advance.

**Comment by Revsgaard** [comment]
Thank you for the future request.

The number of environments (tracks) in an tenant is unlimited. 

If the `FilterTrack` API is extended to support pagination, your problem should be solved. Then the API would return a `paginationToken` which can be send on the next request to query the next page.

Add pagination on all `Filter` APIs.

**Comment by alex-kur** [comment]
Thanks, paging in the `FilterTrack ` API will solve my problem.

**Comment by Revsgaard** [comment]
The next release support pagination with pagination token in a new set of APIs instead of the old set of filter APIs. The new APIs has a plural `s`. For example, the old `FilterTenant` API is now `Tenants` where the new API support pagination.

**Comment by Revsgaard** [comment]
Release in https://github.com/ITfoxtec/FoxIDs/releases/tag/1.13.2
